language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install: "pip install -r ml/requirements.txt"
notifications:
    email: false
script: py.test test/test_ml_task*.py -v
